{% set version = "15.2.0" %}

package:
  name: glslang
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/glslang/archive/{{ version }}.tar.gz
  sha256: 45e3920d264d5c2cc3bfaec0e5dbb66cffd549255e0aaaf38cd283918e35c8ba

build:
  skip: true  # [py!=310]
  number: 0
  run_exports:
    # They seem to use so names with the major version, so lets stick with that
    - {{ pin_subpackage('glslang', 'x') }}
  ignore_run_exports_from:
    - python

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    # Needed as a build tool
    - python
  host:
    - spirv-tools
  run:

test:
  commands:
    - glslangValidator --version
    - test -f ${PREFIX}/lib/libglslang${SHLIB_EXT}             # [unix]
    - test -f ${PREFIX}/lib/libSPIRV${SHLIB_EXT}               # [unix]
    # hmaarrfk: 2023/06
    # I'm not successful at building shared libraries on windows
    - if not exist %PREFIX%\\Library\\lib\\glslang.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\SPIRV.lib   exit 1  # [win]
    # - if not exist %PREFIX%\\Library\\bin\\glslang.dll exit 1  # [win]
    # - if not exist %PREFIX%\\Library\\bin\\SPIRV.dll   exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/glslang
  summary: Glslang Components and Status
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hmaarrfk
